### ISSUE TITLE
'vColor' : undeclared identifier

### ISSUE THREAD

**Issue by Cosmitar** [agargaro/instanced-mesh#11]
When I try to cast shadows a WebGL error says: 'vColor' : undeclared identifier
Here's a codesandbox that shows the error: https://codesandbox.io/p/sandbox/37gxj9

Steps to reproduce:
- navigate to the codesandbox link.
- await for the preview to load and display the scene.
- open CS 'Chrome WebTools for the preview'
- select the Console tab.
- you should see the mentioned error.

Note that if you comment out lines 42 and 45 (were the color is assigned) and reload, the error disappears.
There's a clue I can't fully understand but if you load the preview without assigning color to instances (with commented lines), the boxes are white, then uncomment the mentioned lines and after hot reload the boxes display the right color, shadows and no error is present in the console.

Maybe a race condition during the shader compilation?

Hope this can help to find a bug if it's there.

Great lib btw 🙌

**Comment by Cosmitar** [comment]
I found this: https://github.com/agargaro/instanced-mesh/blob/676e7f326a17b8ad80d5994258299f260a9e6597/src/objects/InstancedMesh2.ts#L22

Is it related to this issue?

**Comment by Cosmitar** [comment]
I made a local fix but not sure if it make sense.
I split this file https://github.com/agargaro/instanced-mesh/blob/master/src/shaders/chunks/instanced_vertex.glsl.ts into two, one with the `instanceMatrix` assign and another one with the `instanceColor`. Then I concatenated the instance color chunk to the 'shadowmap_vertex'.

`shaderChunk.ts`
```ts
import instanced_vertex from "./chunks/instanced_vertex.glsl.js";
import instanced_vertex_color from "./chunks/instanced_vertex_color.glsl.js";

...

ShaderChunk["instanced_vertex"] = instanced_vertex;
ShaderChunk["instanced_vertex_color"] = instanced_vertex_color;

...

ShaderChunk["batching_vertex"] = ShaderChunk["batching_vertex"].concat("\n#include <instanced_vertex>"); // TODO fix d.ts
ShaderChunk["shadowmap_vertex"] = ShaderChunk["shadowmap_vertex"].concat("\n#include <instanced_vertex_color>");
```

What do you think?

**Comment by agargaro** [comment]
Sorry for the delay! I will investigate and let you know asap

**Comment by agargaro** [comment]
@Cosmitar 

The problem occurs when patching a material that has no color (such as `MeshNormalMaterial`, `MeshDepthMaterial`, etc). 

We can avoid patching the color of materials that don't have `#include <color_pars_fragment>` to fix the bug.

Thank you very much for the report and sorry for the late reply (I've not seen the notification 😅). If you need, you can always find me on the discord channel linked in the README 😄

**Comment by agargaro** [comment]
I've released a new version (0.2.4) to fix this.

This is an example to test the fix:
https://stackblitz.com/edit/three-ez-bug-fix-path-color-material?file=src%2Fmain.ts

PS. you can write it also in this way
```js
obj.color = 'red';
```

**Comment by Cosmitar** [comment]
Works fine for me, after updating to 0.2.4 the sandbox shows the shadows as expected with no error. Also tested in local project.

Grazie mille!

**Comment by agargaro** [comment]
Grazie a te! ^^
