### ISSUE TITLE
Question: Force update instnacedUniforms

### ISSUE THREAD

**Issue by OhBonsai** [agargaro/instanced-mesh#37]
HI, @agargaro 

Here is my samlpe code.  i wana update instanced unifrom perioldly. It seems not working. Is there any explicit update function need to call?
```

const PeriodUpdateInstances = ()=>{
  const  renderer  = useThree((state) => state.gl)
  const objs = InstancedMesh2(
      renderer, 1000, new PlaneGeometry(1, 1), new RttMaterial(1000)
  )

  objs.createInstances((obj, index)=>{
    obj.setUniform('vTexture', index);
  })
  objs.computeBVH()

  useEffect(()=>{
    const update = ()=>{
      for (let i = 0; i < 1000; i++) {
        objs.instances[i].setUniform('vTexture', Math.random());
      }
    }

    // do updated every 30 seconds
    const intervalId = setInterval(() => {
      update()
    }, 30000)
    return () => clearInterval(intervalId)

  })
  
  return <primitive object={objs}  />


}

```

**Comment by agargaro** [comment]
Hi!
I should add more documentation about this 🤔 

To use `setUniform` you must use a `DataTexture`. 
There are utility methods to [create](https://github.com/agargaro/instanced-mesh/blob/master/src/utils/CreateTexture.ts) and [use](https://github.com/agargaro/instanced-mesh/blob/master/src/shaders/chunks/get_from_texture.glsl.ts) them and you have to modify the shader (you can use `Material.OnBeforeCompile`).

Is `RttMaterial` a your custom material?

Example that use setUniform: https://stackblitz.com/edit/three-ezinstancedmesh2-custom-material?file=src%2FtileMaterial.ts,src%2Fmain.ts

Later I will try to write a simpler example and create utility methods also to patch existing materials like yours.

Ps. I see that you don't set the object positions and create a BVH. This might slow down.

**Comment by agargaro** [comment]
I have prepared an example where you can set the opacity for each instance:
https://stackblitz.com/edit/three-ezinstancedmesh2-opacity-per-instance?file=src%2Fmain.ts

In your case you should do something similar. 
Lacking utility methods it can be quite complex. 
I will try to improve these things in future versions.

**Comment by OhBonsai** [comment]
@agargaro   Thank you very much for your detailed answers. I think I might not have explained my question clearly. 

I have already read the Minecraft demo[tileMaterial]. 
What I actually want is to regularly update the textures that are transmitted to the shader for storing uniforms. 

Just like the opacity per instanced demo  you mentioned. I want to modify the opacity values at regular intervals.
I see that you have alreday written a comment in this eample 
```
obj.setUniform('opacityTexture', id * 0.1 + 0.1); // can automatic create data texture TODO
```
What I want to know is how to actively trigger an update of the datetexture once. some  function lile `forceUpdateDataTexture()`

**Comment by OhBonsai** [comment]
> I have prepared an example where you can set the opacity for each instance:

```
const intervalId = setInterval(() => {
  console.log('update opacityTexture');
  for (const oneIns in trees.instances) {
    obj.setUniform('opacityTexture', Math.random()); // can automatic create data texture TODO
  }
}, 5000);

```

Just like in your example, I want to update the opacity value every 5 minutes.  It don'st work

```
const intervalId = setInterval(() => {
  const size = Math.ceil(Math.sqrt(count));
  const array = new Float32Array(size * size);
  array.fill(0.5)
  for (let i=0; i<count; i++) {
    array[i] = Math.random();
  }
  console.log('update opacityTexture', array);
  const newData =  new DataTexture(array, size, size, RedFormat, FloatType);
  console.log('update opacityTexture', newData);
  (trees.material as unknown as ShaderMaterial).uniforms.opacityTexture.value = newData;
}, 5000);
```

**Comment by agargaro** [comment]
Create a new texture isn't a good approach.

Yesterday I updated the library (0.2.8) and created a new example:

https://stackblitz.com/edit/three-ezinstancedmesh2-custom-material-zuvyuc?file=src%2FtileMaterial.ts,src%2Fmain.ts

**Comment by OhBonsai** [comment]
> Create a new texture isn't a good approach.
> 
> Yesterday I updated the library (0.2.8) and created a new example:
> 
> https://stackblitz.com/edit/three-ezinstancedmesh2-custom-material-zuvyuc?file=src%2FtileMaterial.ts,src%2Fmain.ts
> 
> Let me know if it works by updating the library and following the example 😄

It' work,ing now  awsome~

**Comment by agargaro** [comment]
@OhBonsai 
I am closing this issue. If you still need support open another bug or join us on our discord server (you can find it in the readme) 😄
