### ISSUE TITLE
Fix visibility management when `perObjectFrustumCulled` is 'false'

### ISSUE THREAD

**Issue by agargaro** [agargaro/instanced-mesh#4]
The visibility of individual instances is not handled correctly if the `perObjectFrustumCulled` property is false.

**Comment by tobiascornille** [comment]
Any idea how hard patching this is?

**Comment by agargaro** [comment]
It doesn't take long, I will fix it as soon as possible if you need it

**Comment by tobiascornille** [comment]
That'd be great! Can also create a PR myself if you can give me some pointers
