### ISSUE TITLE
Best way to tween instance matrix transitions?

### ISSUE THREAD

**Issue by darkvertex** [agargaro/instanced-mesh#5]
I saw "three-ez" had some tweening helpers. Would love to see an example of the ideal way to animate transform transitions between instance matrices updates.

**Comment by agargaro** [comment]
Hi!

The `tween` method is actually extended by the [@three.ez/main](https://github.com/agargaro/three.ez) (a library that will be modularized into several separate packages soon).

In this example, tweens are used to rotate each instance separately.

https://stackblitz.com/edit/three-ezinstancedmesh2-tween?file=src%2Fmain.ts
